---
server:
  applicationConnectors:
    - type: http
      port: 8080
  adminConnectors:
    - type: http
      port: 8081
logging:
  level: INFO
  loggers:
    com.codeflu: DEBUG
  appenders:
    - type: console
      threshold: ALL
      target: stdout
database:
  driverClass: com.mysql.cj.jdbc.Driver
  user: Shrey
  password: Shrey22@
  url: jdbc:mysql://localhost:3306/todolist
  properties:
    charSet: UTF-8

